version: '3'

services:
  # ================================= Bot =====================================
  # Generic Rasa bot, used to run console for example.
  bot:
    build:
      context: .
      dockerfile: ./docker/bot.Dockerfile
    depends_on:
      - actions
    networks: 
      - rasa-network
    public: true
    restart: unless-stopped
    ports:
      - 5005:5005
    command: run --enable-api --cors "*"
  # ================================= Actions =================================
  # Rasa middleware used to connect with external APIs.
  actions:
    build:
      context: .
      dockerfile: ./docker/actions.Dockerfile
    networks: 
      - rasa-network
    restart: unless-stopped
    ports:
      - 5055:5055
  # =============================== Rocket.Chat =================================
  # Rocket.Chat instance.
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:latest
    networks: 
      - rasa-network
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - REG_TOKEN=${REG_TOKEN}
    depends_on:
      - mongo
    ports:
      - 3000:3000
  # =============================== Mongo =================================
  # Mongo database and replica set.
  mongo:
    image: mongo:4.0
    networks: 
      - rasa-network
    restart: unless-stopped
    volumes:
     - ./data/db:/data/db
    command: mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1

  # this container's job is just run the command to initialize the replica set.
  # it will run the command and remove himself (it will not stay running)
  mongo-init-replica:
    image: mongo:4.0
    networks: 
      - rasa-network
    command: >
      bash -c
        "for i in `seq 1 30`; do
          mongo mongo/rocketchat --eval \"
            rs.initiate({
              _id: 'rs0',
              members: [ { _id: 0, host: 'localhost:27017' } ]})\" &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    depends_on:
      - mongo
networks: 
    rasa-network:
        driver: bridge